# Generated by Django 2.1.1 on 2018-09-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
