# Generated by Django 2.1.1 on 2018-09-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180901_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='link',
            new_name='god',
        ),
    ]
