# Generated by Django 2.1.1 on 2018-09-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180901_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='god',
        ),
    ]
